export const DataBuah = [
    {
        id: 1,
        title: "Alpukat",
        quantity: 901,
        image: "images/buah/alpukat.png",
        bgGreen: false,
    },
    {
        id: 2,
        title: "Mangga",
        quantity: 2292,
        image: "images/buah/mangga.png",
        bgGreen: false,
    },
    {
        id: 3,
        title: "Rambutan",
        quantity: 429,
        image: "images/buah/rambutan.png",
        bgGreen: false,
    },
    {
        id: 4,
        title: "Jeruk",
        quantity: 1089,
        image: "images/buah/jeruk.png",
        bgGreen: false,
    },
    {
        id: 5,
        title: "Durian",
        quantity: 468,
        image: "images/buah/durian.png",
        bgGreen: false,
    },
    {
        id: 6,
        title: "Jambu Biji",
        quantity: 65,
        image: "images/buah/jambu-biji.png",
        bgGreen: false,
    },
    {
        id: 7,
        title: "Sawo",
        quantity: 133,
        image: "images/buah/sawo.png",
        bgGreen: false,
    },
    {
        id: 8,
        title: "Pepaya",
        quantity: 149,
        image: "images/buah/pepaya.png",
        bgGreen: false,
    },
    {
        id: 9,
        title: "Kangkung",
        quantity: 296,
        image: "images/buah/kangkung.png",
        bgGreen: false,
    },
    {
        id: 10,
        title: "Pisang",
        quantity: 14280,
        image: "images/buah/pisang.png",
        bgGreen: true,
    },
    {
        id: 11,
        title: "Salak",
        quantity: 241,
        image: "images/buah/salak.png",
        bgGreen: false,
    },
    {
        id: 12,
        title: "Sirsak",
        quantity: 1301,
        image: "images/buah/sirsak.png",
        bgGreen: false,
    },
    {
        id: 13,
        title: "Sukun",
        quantity: 388,
        image: "images/buah/sukun.png",
        bgGreen: false,
    },
    
]