export const DataHoltikultura = [
  {
    id: 1,
    title: "Lombok Besar",
    quantity: 1906,
    image: "images/holtikultura/lombok-besar.png",
    bgGreen: true,
  },
  {
    id: 2,
    title: "Lombok Rawit",
    quantity: 999,
    image: "images/holtikultura/lombok-rawit.png",
    bgGreen: true,
  },
  {
    id: 3,
    title: "Tomat",
    quantity: 95,
    image: "images/holtikultura/tomat.png",
    bgGreen: false,
  },
  {
    id: 4,
    title: "Kacang Panjang",
    quantity: 696,
    image: "images/holtikultura/kacang-panjang.png",
    bgGreen: false,
  },
  {
    id: 5,
    title: "Terong",
    quantity: 744,
    image: "images/holtikultura/terong.png",
    bgGreen: false,
  },
  {
    id: 6,
    title: "Labu Siam",
    quantity: 60,
    image: "images/holtikultura/labu-siam.png",
    bgGreen: false,
  },
  {
    id: 7,
    title: "Bayam",
    quantity: 216,
    image: "images/holtikultura/bayam.png",
    bgGreen: false,
  },
  {
    id: 8,
    title: "Petai",
    quantity: 11420,
    image: "images/holtikultura/patai.png",
    bgGreen: true,
  },
  {
    id: 9,
    title: "Kangkung",
    quantity: 270,
    image: "images/holtikultura/kangkung.png",
    bgGreen: false,
  },
];
